/*-----------------------------------------------------------------------
 * Copyright (C) 2011 Mohamed A. Khamis, EJUST
 *
 * This program (class) is free software.
 * You may redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by
 * the Free Software Foundation (version 2 or later).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *------------------------------------------------------------------------*/

package gld.distributions;

import gld.GLDSim;

import java.util.Random;

/**
 * 
 * @description A Program to generate pseudo-random floating point values, with an approximately Gaussian (normal) distribution.
 * Many physical measurements have an approximately Gaussian distribution; this provides a way of simulating such values. 
*/

public class RandomGaussian {

	/**
	 * @description this method is used to implement a random number generator simulates the values
	 * generated by a Gaussian random generator  
	 */	
	public static Random random = new Random(GLDSim.seriesSeed[GLDSim.seriesSeedIndex]);	
	public static double getGaussian(double mean, double variance){		  	
	      return mean + random.nextGaussian() * variance;
	}
}
