/*-----------------------------------------------------------------------
 * Copyright (C) 2011 Mohamed A. Khamis, EJUST
 *
 * This program (class) is free software.
 * You may redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by
 * the Free Software Foundation (version 2 or later).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *------------------------------------------------------------------------*/

package gld.distributions;

/** 
 * @description A Program to simulate the values generated by Exponential (X) random variable 
 * using a Uniform random variable (Inverse Transform Method)
 * */
public class RandomExponential {
	/**
	 * @param Lambda > 0 rate, or inverse scale
	 */
	public static double getExponential (double lambda){				
		return - (1.0/lambda)*Math.log(RandomUniform.getUniform(0, 1));		
	}
}
